
name: 00 Publish 02 docs (Storybook) to GitHub Pages
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Append name of site to _config.yml
        working-directory: ./frontend/docs-index
        run: | 
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> _config.yml
          echo "owner: ${OWNER}" >> _config.yml
          echo "repo_name: ${REPOSITORY}" >> _config.yml
      - name: Deploy index.md and jekyll files for production docs site ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/docs-index 
          clean: false 
          target-folder: docs
      - name: Deploy index.md for docs site ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/docs-index 
          clean: true 
          target-folder: docs
      - name: Install and Build ðŸ”§
        working-directory: ./frontend
        run: | # Install npm packages and build the Storybook files
          npm install
          mkdir -p docs-build
          npm run build-storybook
      - name: Deploy ðŸš€ 
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs/storybook # The folder that we serve our Storybook files from  
